FROM python:3.11

WORKDIR /server/

COPY . /server

RUN pip3 install fastapi
RUN pip3 install uvicorn
RUN pip3 install websockets
RUN pip3 install pymysql
RUN pip3 install redis
RUN pip install pytz
RUN pip install APScheduler

ENV MYSQL_PASSWORD=Xy3@9#pZ$7!

CMD ["bash", "main_work.sh"]