FROM mysql:5.7.30

WORKDIR /docker-entrypoint-initdb.d
ENV MYSQL_ROOT_PASSWORD=Xy3@9#pZ$7!

ADD ./mysql_conf.sql /docker-entrypoint-initdb.d/
ADD ./graduation_project_conf.sql /docker-entrypoint-initdb.d/


RUN echo "[mysqld]" >> /etc/mysql/my.cnf
RUN echo "character-set-server=utf8mb4" >> /etc/mysql/my.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/my.cnf
RUN echo "[client]" >> /etc/mysql/my.cnf
RUN echo "default-character-set=utf8mb4" >> /etc/mysql/my.cnf

